### ISSUE TITLE
error while replicating react openseadragon example

### ISSUE THREAD

**Issue by BasLee** [annotorious/annotorious#489]
**Which version of Annotorious are you using?**
- `"@annotorious/react": "3.0.19"`
- `"openseadragon": "5.0.0"`

**Issue behavior**
When I try to recreate the examples on https://annotorious.dev/react/openseadragon-iiif/ , this error is thrown:
```
No drawing tool named undefined
```
I recreated it in this sandbox: https://codesandbox.io/p/sandbox/lpdfx9

**Screenshots**
( Screenshot from https://codesandbox.io/p/sandbox/lpdfx9 )

![image](https://github.com/user-attachments/assets/a1a459d0-9a50-460b-a615-4fdab42c9c85)

**Comment by rsimon** [comment]
Hi, thanks for reporting. That's a small regression that crept in. It's [already fixed in the source code](https://github.com/annotorious/annotorious/commit/8ea7b81018dbb1d6e35b530c59dcedcf169183ef), and will go live with the next release. For now, you can work around the problem by setting the tool as "rectangle" by default.

**Comment by BasLee** [comment]
Thank you for the quick reply! 
I added the rectangle prop to the sandbox like this `<OpenSeadragonAnnotator tool="rectangle">`. The error is gone now, but the image is still not showing up?

**Comment by rsimon** [comment]
Your app container has a size of 0 x 0 pixels.

**Comment by BasLee** [comment]
A, I see, that did the trick :)

**Comment by BasLee** [comment]
~Not related to the bug mentioned above, so I can create a new issue... but how to deselect a selected annotation in the react openseadragon annotator setup? 
In the [codesandbox](https://codesandbox.io/p/sandbox/lpdfx9) I recreated the react openseadragon example with a custom comment popup, and now I can create a new annotation, but deselecting  and creating a second annotation seems to be broken? Or maybe I missed something?
Clicking outside of the rectangle does not work and clicking on the top-left bottom does not work.~
The popup covered seadragon elements.

**Comment by rsimon** [comment]
Just to confirm: so this is resolved and works as it should?
